title: Shridhar Suregaonkar
description: Computer Science Engineer | Researcher | Developer
url: "https://yourusername.github.io"
baseurl: ""

# Personal info
email: shridharsuregaonkar@gmail.com
phone: 7483479427
github_username: yourgithubusername
linkedin_username: yourlinkedinprofile
education:
  - degree: BE, Computer Science and Engineering
    university: KLE Technological University
    cgpa: 8.71
    duration: Nov 2022 - May 2026
